
services:
  mongo:
    image: mongo
    container_name: kidsyncapp-mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env.local

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env.local
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.238  # <--- your host LAN IP
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "8081:8081"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules  # named volume
    command: sh -c "npm install && npx expo start --tunnel"
    env_file:
      - .env.local
    depends_on:
      - backend

volumes:
  frontend_node_modules:
